version: 2
updates:
  - package-ecosystem: "poetry"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: ".github/workflows/"
    schedule:
      interval: "weekly"
